[package]
name = "HockeyStat"
version = "0.1.0"
authors = ["Niklas Larsson <niklaslarsson95@gmail.com>"]

[dependencies]
curl = "*"
serde_json = "1.0"
serde_derive = "*"
serde = "*"
time = "*"
chrono = { version = "*", features = ["serde"] }
plotlib = "*"
